name: DigitalOcean App Platform deployment
description: Deploy an application to DigitalOcean's App Platform.
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  token:
    description: DigitalOcean Personal Access Token. See https://docs.digitalocean.com/reference/api/create-personal-access-token/ for creating a new token.
    required: true
  app_spec_location:
    description: Location of the app spec file. Mutually exclusive with `app_name`.
    required: false
    default: '.do/app.yaml'
  project_id:
    description: ID of the project to deploy the app to. If not given, the app will be deployed to the default project.
    required: false
    default: ''
  app_name:
    description: Name of the app to pull the spec from. The app must already exist. If an app name is given, a potential in-repository app spec is ignored.
    required: false
    default: ''
  print_build_logs:
    description: Print build logs.
    required: false
    default: 'false'
  print_deploy_logs:
    description: Print deploy logs.
    required: false
    default: 'false'
  deploy_pr_preview:
    description: Deploy the app as a PR preview. The app name will be derived from the PR, the app spec will be mangled to exclude conflicting configuration like domains and alerts and all Github references to the current repository will be updated to point to the PR's branch.
    required: false
    default: 'false'

outputs:
  app:
    description: A JSON representation of the entire app after the deployment.
    value: ${{ steps.deploy.outputs.app }}
  url:
    description: The URL to the newly deployed app.
    value: ${{ steps.deploy.outputs.url }}
  build_logs:
    description: The builds logs of the deployment.
    value: ${{ steps.deploy.outputs.build_logs }}
  deploy_logs:
    description: The deploy logs of the deployment.
    value: ${{ steps.deploy.outputs.deploy_logs }}

runs:
  using: composite
  steps:
    - name: Cache
      id: build-cache
      uses: actions/cache@v4
      with:
        path: ./deploy
        key: digitalocean-app-action.deploy-cache-${{ runner.os }}

    - name: Build
      if: steps.build-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        docker build -t digitalocean-app-action:latest "${{ github.action_path }}/../"
        container_id=$(docker create digitalocean-app-action:latest)
        docker cp $container_id:/usr/local/bin/deploy ./deploy
        docker rm $container_id

    - name: Make executable
      if: steps.build-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        chmod +x ./deploy

    - name: Run binary
      id: deploy
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_APP_SPEC_LOCATION: ${{ inputs.app_spec_location }}
        INPUT_PROJECT_ID: ${{ inputs.project_id }}
        INPUT_APP_NAME: ${{ inputs.app_name }}
        INPUT_PRINT_BUILD_LOGS: ${{ inputs.print_build_logs }}
        INPUT_PRINT_DEPLOY_LOGS: ${{ inputs.print_deploy_logs }}
        INPUT_DEPLOY_PR_PREVIEW: ${{ inputs.deploy_pr_preview }}

      run: ./deploy
